# Generated by Django 6.0.5 on 2026-06-09 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presupuesto',
            old_name='telefono',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='estado_item',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='comprobante_url',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='curso',
        ),
        migrations.AddField(
            model_name='pago',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_envio_comprobante',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='diseno',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido'), ('en_revision', 'En revisión')], default='pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='colegio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('anio', models.IntegerField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('armando', 'Armando'), ('presupuestada', 'Presupuestada'), ('confirmada', 'Confirmada'), ('produccion', 'Producción'), ('finalizada', 'Finalizada')], default='armando', max_length=30)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.colegio')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.promocion'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='promo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.promocion'),
        ),
    ]
