# Generated by Django 4.2.4 on 2026-05-26 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('anio', models.IntegerField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('armando', 'Armando'), ('presupuestada', 'Presupuestada'), ('confirmada', 'Confirmada'), ('produccion', 'Producción'), ('finalizada', 'Finalizada')], default='armando', max_length=30)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.colegio')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.promocion'),
        ),
    ]
