# Generated by Django 5.2.10 on 2026-05-20 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colegio',
            name='estado',
        ),
    ]
