# Generated by Django 4.2.4 on 2026-05-27 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_promocion_curso_promocion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='curso',
        ),
        migrations.AddField(
            model_name='pedido',
            name='promo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.promocion'),
        ),
    ]
