# Generated by Django 5.2.10 on 2026-05-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_colegio_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='apodo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
