# Generated by Django 4.2.4 on 2026-05-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_pedido_curso_pedido_promo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='estado_item',
        ),
    ]
