# Generated by Django 5.2.10 on 2026-05-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_detallepedido_apodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='estado_general',
        ),
    ]
