# Generated by Django 6.0.5 on 2026-06-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_detallepedido_estado_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='colegio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
