# Generated by Django 5.2.10 on 2026-05-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_alumno_estado_general'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='apodo',
        ),
    ]
