# Generated by Django 5.2.10 on 2026-06-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_detallepedido_estado_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='comprobante_url',
        ),
        migrations.AddField(
            model_name='pago',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_envio_comprobante',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido'), ('en_revision', 'En revisión')], default='pendiente', max_length=30),
        ),
    ]
