# Generated by Django 5.2.10 on 2026-05-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_alumno_apodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='estado_item',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_produccion', 'En producción'), ('listo', 'Listo'), ('entregado', 'Entregado')], default='pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_produccion', 'En producción'), ('entregado', 'Entregado')], default='pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=30),
        ),
    ]
