# Generated by Django 6.0.5 on 2026-06-09 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_presupuesto_colegio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presupuesto',
            old_name='telefono',
            new_name='email',
        ),
    ]
