# Generated by Django 6.0.5 on 2026-06-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_telefono_presupuesto_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='archivo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
