# Generated by Django 5.2.10 on 2026-06-09 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_pago_comprobante_url_pago_comprobante_and_more'),
        ('core', '0006_rename_telefono_presupuesto_email'),
    ]

    operations = [
    ]
