# Generated by Django 6.0.5 on 2026-06-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_presupuesto_archivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presupuesto',
            old_name='archivo',
            new_name='diseno',
        ),
    ]
